import React from 'react';
import { Section, Container } from 'react-bulma-components';

export default function Overview () {
    return (
        <Section>
          <Container>
            <div>
              <p style={{fontSize:16, lineHeight:'16px'}}>
                <pre>{x.join('\n')}</pre>
              </p>
            </div>
          </Container>
        </Section>
    );
}

const x = [
    '        +---------+                            +--------+    +------+',
    '        | Atman   |                            | Umpire |    | Pool |',
    '        |=========|                            |========|    |======|',
    '        |- _id    |                            |--------|    |------|',
    '        |- _core  |                            |        |    +------+',
    '        |- _class |                            |        |',
    '        |---------|                            +--------+',
    '        |+ id     |',
    '        +---------+',
    '             ^',
    '             |',
    '             +-------------------------+-----------------------------------+---------------------------------+----------------------+',
    '             |                         |                                   |                                 |                      |',
    '  +----------------------+     +----------------+                      +--------+                  +------------------+     +--------------+',
    '  | Entity               |     | ColumnInstance |           +----------| Column |                  | Port             |     | Relationship |',
    '  |======================|     |================|           |          |========|                  |==================|     |==============|',
    '  |+ padding             |     |- _master       |<----------+          |+ name  |                  |- _owner          |     |+ from        |',
    '  |+ margin              |     |+ name          |                      |--------|                  |- _type           |     |+ to          |',
    '  |+ description         |     |----------------|                      +--------+                  |- _entity         |     |--------------|',
    '  |+ position            |     +----------------+                          |                       |+ position        |     +--------------+',
    '  |+ size                |             ^                                   |                       |------------------|',
    '  |+ bar                 |             |   +--------------------+          |     +------------+    |+ position_degree |',
    '  |+ background          |             +---| IdentifierInstance |          +-----| Identifier |    +------------------+',
    '  |+ name                |   +---------|---|====================|          |     |============|',
    '  |+ type                |   |         |   |--------------------|          |     |------------|',
    '  |+ identifiers         |   |         |   +--------------------+          |     +------------+',
    '  |+ attributes          |   |         |                                   |',
    '  |+ ports               |   |         |   +-------------------+           |     +-----------+',
    '  |+ identifier_instance |<--+         +---| AttributeInstance |           +-----| Attribute |',
    '  |+ Attribute_instance  |<----------------|===================|                 |===========|',
    '  |- sculptor            |                 |-------------------|                 |-----------|',
    '  |- builder             |                 +-------------------+                 +-----------+',
    '  |----------------------|',
    '  |+ sizing              |<------------+',
    '  |+ reSizing            |<----------+ |',
    '  |+ positioning         |<--------+ | |',
    '  |+ build               |<--------|-|-|----------------------------------+',
    '  |- init                |         | | |                                  |',
    '  |- template            |         | | |   +--------------------------+   |   +---------------------+         +--------------+',
    '  +----------------------+         | | |   | Tailor                   |   |   | Builder             |         | Sculptor     |',
    '                                   | | |   |==========================|   |   |=====================|         |==============|',
    '                                   | | |   |--------------------------|   |   |---------------------|         |--------------|',
    '                                   | | |   |                          |   |   |+ entityTypeContents |         |+ pool        |',
    '                                   | | |   |- sizingType              |   |   |+ entityBackground   |         |+ position    |',
    '                                   | | |   |- sizingName              |   |   |- buildIdentifiers   |         |+ size        |',
    '                                   | | |   |- sizingIdentifiers       |   |   |- buildAttributes    |         |+ background  |',
    '                                   | | |   |- sizingAttributes        |   +---|+ build              |         |+ bar         |',
    '                                   | | |   |- sizingContentsArea      |       +---------------------+         |+ type        |',
    '                                   | | +---|+ sizing                  |                                       |+ identifiers |',
    '                                   | +-----|+ reSizing                |                                       |+ attributes  |',
    '                                   |       |                          |                                       |+ ports       |',
    '                                   |       |+ positioningName         |                                       +--------------+',
    '                                   |       |+ positioningType         |',
    '                                   |       |+ positioningColumnItems  |',
    '                                   |       |+ positioningIdentifiers  |',
    '                                   |       |+ positioningAttributes   |',
    '                                   |       |+ deg2rad                 |',
    '                                   |       |+ getPortLineLength       |',
    '                                   |       |+ getPortLineFrom         |',
    '                                   |       |+ makePortLine            |',
    '                                   |       |+ isCorss                 |',
    '                                   |       |+ getCrossPointCore       |',
    '                                   |       |+ getCrossPoint           |',
    '                                   |       |+ getEntityLines          |',
    '                                   |       |+ positioningPort         |',
    '                                   |       |+ positioningPorts        |',
    '                                   |       |+ positioningEntity       |',
    '                                   +-------|+ positioning             |',
    '                                           +--------------------------+',
    '       +-------+',
    '       | Colon |',
    '       |=======|',
    '       |-------|',
    '       +-------+',
    '           ^',
    '           |',
    '  +-----------------------------+',
    '  | Rectum                      |',
    '  |=============================|',
    '  |+ callbacks                  |',
    '  |- _entities                  |',
    '  |- _relationships             |',
    '  |- _default                   |',
    '  |-----------------------------|',
    '  |- ensureCallbacks            |',
    '  |+ entities                   |',
    '  |+ bounds                     |',
    '  |+ getIdentifier              |',
    '  |- buildRelationshipsWithPort |',
    '  |+ data                       |',
    '  +-----------------------------+',
];
