const BUILDER = [               
    '     Atman                 ',
    '       |                   ',
    '+---------------------+    ',
    '| Builder             |    ',
    '|=====================|    ',
    '|+ name               |    ',
    '|+ description        |    ',
    '|+ position           |    ',
    '|+ size               |    ',
    '|+ type               |    ',
    '|+ background         |    ',
    '|---------------------|    ',
    '|+ init               |    ',
    '|+ template           |    ',
    '|- entityTypeContents |    ',
    '|- entityBackground   |    ',
    '|- buildIdentifiers   |    ',
    '|- buildAttributes    |    ',
    '|- build              |    ',
    '+---------------------+    ',
    '       ^                   ',
    '       |                   ',
    '+-------------------------+',
    '| EntityTailor            |',
    '|=========================|',
    '|<Size>                   |',
    '|- sizingType             |',
    '|  sizingName             |',
    '|  sizingIdentifiers      |',
    '|  sizingAttributes       |',
    '|  sizingContentsArea     |',
    '|+ sizing                 |',
    '|+ reSizing               |',
    '|                         |',
    '|<Position>               |',
    '|- positioningName        |',
    '|  positioningType        |',
    '|  positioningColumnItems |',
    '|  positioningIdentifiers |',
    '|  positioningAttributes  |',
    '|  deg2rad                |',
    '|  getPortLineLength      |',
    '|  getPortLineFrom        |',
    '|  makePortLine           |',
    '|  isCorss                |',
    '|  getCrossPointCore      |',
    '|  getCrossPoint          |',
    '|  getEntityLines         |',
    '|  positioningPort        |',
    '|  positioningPorts       |',
    '|  positioningEntity      |',
    '|+ positioning            |',
    '+-------------------------+',
    '       ^                   ',
    '       |                   ',
    '    Entity                 ',
];                     
                       
export default BUILDER;
