const BUILDER = [
    '     Atman                 ',
    '       |                   ',
    '+---------------------+    ',
    '| Builder             |    ',
    '|=====================|    ',
    '|+ name               |    ',
    '|+ description        |    ',
    '|+ position           |    ',
    '|+ size               |    ',
    '|+ type               |    ',
    '|+ background         |    ',
    '|---------------------|    ',
    '|+ init               |    ',
    '|+ template           |    ',
    '|- entityTypeContents |    ',
    '|- entityBackground   |    ',
    '|- buildIdentifiers   |    ',
    '|- buildAttributes    |    ',
    '|- build              |    ',
    '+---------------------+    ',
    '       ^                   ',
    '       |                   ',
    '    Entity                 ',
];

export default BUILDER;
