const MATERIAL = [
    '                                              +---------+',
    '                                              | Atman   |',
    '                                              |=========|',
    '                                              |- _class |',
    '                                              |- _id    |',
    '                                              |- _core  |',
    '                                              |---------|',
    '                                              |+ id     |',
    '                                              +---------+',
    '                                                   ^',
    '                                                   |',
    '       +--------------------------+----------------+--+---------------+-----------+---------------------+',
    '       |                          |                   |               |           |                     |',
    '       |                     +----------------+  +-----------+  +------------+    |                     |',
    '    Builder                  | ColumnInstance |  | Attribute |  | Identifier |    |                     |',
    '       |                     |================|  |===========|  |============|    |                     |',
    '       |                     |+ name          |  |+ name     |  |+ name      |    |                     |',
    '       |                     |- _master       |  |-----------|  |------------|    |                     |',
    '       |                     |----------------|  +-----------+  +------------+    |                     |',
    '       |                     +----------------+                                   |                     |',
    '       |                          ^                                               |                     |',
    '       |                          |                                               |                     |',
    '       |                          +----------------------+                        |                     |',
    '       |                          |                      |                        |                     |',
    '+-------------------------+  +-------------------+  +--------------------+  +------------------+  +--------------+',
    '| Entity                  |  | AttributeInstance |  | IdentifierInstance |  | Port             |  | Relationship |',
    '|=========================|  |===================|  |====================|  |==================|  |==============|',
    '|- _default               |  |+ name             |  |+ name              |  |- _id             |  |+ from        |',
    '|-------------------------|  |+ position         |  |+ position          |  |- _owner          |  |+ to          |',
    '|<Size>                   |  |+ size             |  |+ size              |  |- _type           |  |--------------|',
    '|- sizingType             |  |-------------------|  |- _ports            |  |- _core           |  +--------------+',
    '|  sizingName             |  |+ template         |  |--------------------|  |+ position        |',
    '|  sizingIdentifiers      |  +-------------------+  +--------------------+  |- _entity         |',
    '|  sizingAttributes       |                                                 |------------------|',
    '|  sizingContentsArea     |                                                 |+ position_degree |',
    '|+ sizing                 |                                                 +------------------+',
    '|+ reSizing               |',
    '|                         |',
    '|<Position>               |',
    '|- positioningName        |',
    '|  positioningType        |',
    '|  positioningColumnItems |',
    '|  positioningIdentifiers |',
    '|  positioningAttributes  |',
    '|  deg2rad                |',
    '|  getPortLineLength      |',
    '|  getPortLineFrom        |',
    '|  makePortLine           |',
    '|  isCorss                |',
    '|  getCrossPointCore      |',
    '|  getCrossPoint          |',
    '|  getEntityLines         |',
    '|  positioningPort        |',
    '|  positioningPorts       |',
    '|  positioningEntity      |',
    '|+ positioning            |',
    '+-------------------------+',
];

export default MATERIAL;
