const MATERIAL = [
    '                                              +---------+',
    '                                              | Atman   |',
    '                                              |=========|',
    '                                              |- _class |',
    '                                              |- _id    |',
    '                                              |- _core  |',
    '                                              |---------|',
    '                                              |+ id     |',
    '                                              +---------+',
    '                                                   ^',
    '                                                   |',
    '       +--------------------------+----------------+--+---------------+-----------+---------------------+',
    '       |                          |                   |               |           |                     |',
    '       |                     +----------------+  +-----------+  +------------+    |                     |',
    '       |                     | ColumnInstance |  | Attribute |  | Identifier |    |                     |',
    '       |                     |================|  |===========|  |============|    |                     |',
    '       |                     |+ name          |  |+ name     |  |+ name      |    |                     |',
    '       |                     |- _master       |  |-----------|  |------------|    |                     |',
    '       |                     |----------------|  +-----------+  +------------+    |                     |',
    '       |                     +----------------+                                   |                     |',
    '       |                          ^                                               |                     |',
    '       |                          |                                               |                     |',
    '       |                          +----------------------+                        |                     |',
    '       |                          |                      |                        |                     |',
    '+-------------------------+  +-------------------+  +--------------------+  +------------------+  +--------------+',
    '| Entity                  |  | AttributeInstance |  | IdentifierInstance |  | Port             |  | Relationship |',
    '|=========================|  |===================|  |====================|  |==================|  |==============|',
    '|- _default               |  |+ name             |  |+ name              |  |- _id             |  |+ from        |',
    '|                         |  |+ position         |  |+ position          |  |- _owner          |  |+ to          |',
    '|+ name                   |  |+ size             |  |+ size              |  |- _type           |  |--------------|',
    '|+ description            |  |-------------------|  |- _ports            |  |- _core           |  +--------------+',
    '|+ position               |  |+ template         |  |--------------------|  |+ position        |',
    '|+ size                   |  +-------------------+  |+ template          |  |- _entity         |',
    '|+ type                   |                         +--------------------+  |------------------|',
    '|+ background             |                                                 |+ position_degree |',
    '|---------------------    |                                                 |  addPort2Entity  |',
    '|<Builder>                |                                                 |                  |',
    '|+ init                   |                                                 |<???>             |',
    '|+ template               |                                                 |  calLinePoints   |',
    '|- entityTypeContents     |                                                 |  calOneLine      |',
    '|- entityBackground       |                                                 |  calThreeLine    |',
    '|- buildIdentifiers       |                                                 |  calCircle       |',
    '|- buildAttributes        |                                                 +------------------+',
    '|- build                  |                                                                     ',
    '|                         |                                                                     ',
    '|<Size>                   |                                                                     ',
    '|- sizingType             |                                                                     ',
    '|  sizingName             |                                                                     ',
    '|  sizingIdentifiers      |                                                                     ',
    '|  sizingAttributes       |                                                                     ',
    '|  sizingContentsArea     |                                                                     ',
    '|+ sizing                 |                                                                     ',
    '|+ reSizing               |                                                                     ',
    '|                         |                                                                     ',
    '|<Position>               |',
    '|  positioningType        |',
    '|- positioningName        |',
    '|  positioningColumnItems |',
    '|  positioningIdentifiers |',
    '|  positioningAttributes  |',
    '|  positioningPort        |',
    '|  positioningPorts       |',
    '|  positioningEntity      |',
    '|+ positioning            |',
    '+-------------------------+',
];

export default MATERIAL;
