const PAINTER = [
    '+----------------+       +----------------------+',
    '| Painter        |       | Entity               |',
    '|================|       |======================|',
    '|+ foreground    |       |- _parent             |',
    '|+ background    |       |----------------------|',
    '|+ callbacks     |       |- foreground          |',
    '|- _default      |       |- background          |',
    '|_painters       |       |- callbacks           |',
    '|----------------|       |- default             |',
    '|- ports         |<--+   |                      |',
    '|- relationships |   |   |<Move>                |',
    '|- entity        |   |   |- dragStart           |',
    '|+ draw          |   |   |- dragged             |',
    '+----------------+   |   |- dragEnd             |',
    '                     |   |- addMoveEvents       |',
    '                     +--||  moveEntity          |',
    '                        ||  moveEdges           |',
    '                         |                      |',
    '                         |<Draw this.entity>    |',
    '                         |  drawGroup           |',
    '                         |                      |',
    '                         |<Body>                |',
    '                         |  drawBodyCore        |',
    '                         |  drawBody            |',
    '                         |                      |',
    '                         |<Name>                |',
    '                         |  drawNameRect        |',
    '                         |  drawNameText        |',
    '                         |  drawName            |',
    '                         |                      |',
    '                         |<Type>                |',
    '                         |  drawTypeRect        |',
    '                         |  drawTypeText        |',
    '                         |  drawType            |     +------------------------+',
    '                         |                      |     | Identifiers            |',
    '                         |<Identifiers>         |     |========================|',
    '                         |  drawIdentifiersRect ||--->|------------------------|',
    '                         |  drawIdentifiersText ||    |+ draw                  |',
    '                         |  drawIdentifiers     |     +------------------------+',
    '                         |                      |',
    '                         |<Attributes>          |     +------------------------+',
    '                         |  drawAttributesRect  ||--->| Attributes             |',
    '                         |  drawAttributesText  ||    |========================|',
    '                         |  drawAttributes      |     |------------------------|',
    '                         |                      |     |+ draw                  |',
    '                         |<Draw Main>           |     +------------------------+',
    '                         |+ redraw              |',
    '                         |+ draw                |',
    '                         +----------------------+',
    '',
    '                         +------------------------+',
    '                         | Relationships          |',
    '                         |========================|',
    '                         |- _parent               |',
    '                         |------------------------|',
    '                         |+ drawRelationshipsCore |',
    '                         |+ drawRelationships     |',
    '                         +------------------------+',
    '',
    '                         +----------------+',
    '                         | Ports          |',
    '                         |================|',
    '                         |- _parent       |',
    '                         |----------------|',
    '                         |# drawPortsCore |',
    '                         |+ drawPorts     |',
    '                         +----------------+',
];

export default PAINTER;
