import React from 'react';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';

export default function Classes () {
    return (
        <Container maxWidth="md"
                   sx={{pt: 3, pb: 22}}>
          <Box>
            <pre style={{lineHeight: '13px'}}>
              {x.join('\n')}
            </pre>
          </Box>
        </Container>
    );
}

const x = [
    '                                                                    utils/',
    '                                                                    +-----------+  +------------+  +----------+  +------+',
    '                                                                    | Name      |  | Pool       |  | Position |  | Size |',
    '     +---------+                                                    |===========|  |============|  |==========|  |======|',
    '     | Atman   |                                                    |+ physical |  |------------|  |+ x       |  |+ h   |',
    '     |=========|                                                    |+ logical  |  |+ make      |  |+ y       |  |+ w   |',
    '     |- _class |                                                    |+ padding  |  |+ list2pool |  |+ z       |  |------|',
    '     |- _id    |                                                    |+ position |  +------------+  |----------|  +------+',
    '     |- _core  |                                                    |+ size     |                  +----------+',
    '     |---------|                                                    |-----------|',
    '     |+ id     |                                                    |+ set      |',
    '     +---------+                                                    |+ val      |',
    '          ^                                                         +-----------+',
    '          |',
    '          +--------------------------+-------------------+---------------+---------------+---------------------+',
    '          |                          |                   |               |               |                     |',
    '   +---------------------+      +----------------+  +-----------+  +------------+  +------------------+  +--------------+',
    '   | Builder             |      | ColumnInstance |  | Attribute |  | Identifier |  | Port             |  | Relationship |',
    '   |=====================|      |================|  |===========|  |============|  |==================|  |==============|',
    '   |+ name               |      |+ name          |  |+ name     |  |+ name      |  |- _id             |  |+ from        |',
    '   |+ description        |      |- _master       |  |-----------|  |------------|  |- _owner          |  |+ to          |',
    '   |+ position           |      |----------------|  +-----------+  +------------+  |- _type           |  |--------------|',
    '   |+ size               |      +----------------+                                 |- _core           |  +--------------+',
    '   |+ type               |           ^                                             |+ position        |',
    '   |+ background         |           |                                             |- _entity         |',
    '   |---------------------|           +------------------------+                    |------------------|',
    '   |+ init               |           |                        |                    |+ position_degree |',
    '   |+ template           |      +-------------------+    +--------------------+    +------------------+',
    '   |- entityTypeContents |      | AttributeInstance |    | IdentifierInstance |',
    '   |- entityBackground   |      |===================|    |====================|',
    '   |- buildIdentifiers   |      |+ name             |    |+ name              |',
    '   |- buildAttributes    |      |+ position         |    |+ position          |',
    '   |- build              |      |+ size             |    |+ size              |',
    '   +---------------------+      |-------------------|    |- _ports            |',
    '          ^                     |+ template         |    |--------------------|',
    '          |                     +-------------------+    +--------------------+',
    '   +-------------------------+',
    '   | EntityTailor            |',
    '   |=========================|',
    '   |<Size>                   |',
    '   |- sizingType             |',
    '   |  sizingName             |      +-----------------------------+',
    '   |  sizingIdentifiers      |      | Rectum (Colon)              |',
    '   |  sizingAttributes       |      |=============================|',
    '   |  sizingContentsArea     |      |+ callbacks                  |',
    '   |+ sizing                 |      |- _entities                  |',
    '   |+ reSizing               |      |- _relationships             |',
    '   |                         |      |- _default                   |',
    '   |<Position>               |      |-----------------------------|',
    '   |- positioningName        |      |  ensureCallbacks            |',
    '   |  positioningType        |      |  entities                   |',
    '   |  positioningColumnItems |      |  bounds                     |',
    '   |  positioningIdentifiers |      |  getIdentifier              |',
    '   |  positioningAttributes  |      |  buildRelationshipsWithPort |',
    '   |  deg2rad                |      |+ data                       |',
    '   |  getPortLineLength      |      |  draw                       |',
    '   |  getPortLineFrom        |      +-----------------------------+',
    '   |  makePortLine           |',
    '   |  isCorss                |',
    '   |  getCrossPointCore      |',
    '   |  getCrossPoint          |',
    '   |  getEntityLines         |',
    '   |  positioningPort        |',
    '   |  positioningPorts       |',
    '   |  positioningEntity      |',
    '   |+ positioning            |',
    '   +-------------------------+',
    '          ^',
    '          |',
    '   +-----------+',
    '   | Entity    |',
    '   |===========|',
    '   |- _default |',
    '   |-----------|',
    '   +-----------+',
    '',
    '',
    '+----------------+       +----------------------+   +------------------------+   +----------------+',
    '| Painter        |       | Entity               |   | Relationships          |   | Ports          |',
    '|================|       |======================|   |========================|   |================|',
    '|+ foreground    |       |- _parent             |   |- _parent               |   |- _parent       |',
    '|+ background    |       |----------------------|   |------------------------|   |----------------|',
    '|+ callbacks     |       |- foreground          |   |+ drawRelationshipsCore |   |# drawPortsCore |',
    '|- _default      |       |- background          |   |+ drawRelationships     |   |+ drawPorts     |',
    '|_painters       |       |- callbacks           |   +------------------------+   +----------------+',
    '|----------------|       |- default             |',
    '|- ports         |<--+   |                      |',
    '|- relationships |   |   |<Move>                |',
    '|- entity        |   |   |- dragStart           |',
    '|+ draw          |   |   |- dragged             |',
    '+----------------+   |   |- dragEnd             |',
    '                     |   |- addMoveEvents       |',
    '                     +--||  moveEntity          |',
    '                        ||  moveEdges           |',
    '                         |                      |',
    '                         |<Draw this.entity>    |',
    '                         |  drawGroup           |',
    '                         |                      |',
    '                         |<Body>                |',
    '                         |  drawBodyCore        |',
    '                         |  drawBody            |',
    '                         |                      |',
    '                         |<Name>                |',
    '                         |  drawNameRect        |',
    '                         |  drawNameText        |',
    '                         |  drawName            |',
    '                         |                      |',
    '                         |<Type>                |',
    '                         |  drawTypeRect        |',
    '                         |  drawTypeText        |',
    '                         |  drawType            |           +------------------------+',
    '                         |                      |           | Identifiers            |',
    '                         |<Identifiers>         |           |========================|',
    '                         |  drawIdentifiersRect ||--------->|------------------------|',
    '                         |  drawIdentifiersText ||          |+ draw                  |',
    '                         |  drawIdentifiers     |           +------------------------+',
    '                         |                      |',
    '                         |<Attributes>          |           +------------------------+',
    '                         |  drawAttributesRect  ||--------->| Attributes             |',
    '                         |  drawAttributesText  ||          |========================|',
    '                         |  drawAttributes      |           |------------------------|',
    '                         |                      |           |+ draw                  |',
    '                         |<Draw Main>           |           +------------------------+',
    '                         |+ redraw              |',
    '                         |+ draw                |',
    '                         +----------------------+',
];
