import React from 'react';
import Box from '@mui/material/Box';

export default function Classes () {
    return (
        <Box>
          <pre style={{lineHeight: '13px'}}>
            {x.join('\n')}
          </pre>
        </Box>
    );
}

const x = [
    '                                                                    utils/',
    '                                                                    +-----------+  +------------+  +----------+  +------+',
    '                                                                    | Name      |  | Pool       |  | Position |  | Size |',
    '     +---------+                                                    |===========|  |============|  |==========|  |======|',
    '     | Atman   |                                                    |+ physical |  |------------|  |+ x       |  |+ h   |',
    '     |=========|                                                    |+ logical  |  |+ make      |  |+ y       |  |+ w   |',
    '     |- _class |                                                    |+ padding  |  |+ list2pool |  |+ z       |  |------|',
    '     |- _id    |                                                    |+ position |  +------------+  |----------|  +------+',
    '     |- _core  |                                                    |+ size     |                  +----------+',
    '     |---------|                                                    |-----------|',
    '     |+ id     |                                                    |+ set      |',
    '     +---------+                                                    |+ val      |',
    '          ^                                                         +-----------+',
    '          |',
    '          +--------------------------+-------------------+---------------+---------------+---------------------+',
    '          |                          |                   |               |               |                     |',
    '   +---------------------+      +----------------+  +-----------+  +------------+  +------------------+  +--------------+',
    '   | Builder             |      | ColumnInstance |  | Attribute |  | Identifier |  | Port             |  | Relationship |',
    '   |=====================|      |================|  |===========|  |============|  |==================|  |==============|',
    '   |+ name               |      |+ name          |  |+ name     |  |+ name      |  |- _id             |  |+ from        |',
    '   |+ description        |      |- _master       |  |-----------|  |------------|  |- _owner          |  |+ to          |',
    '   |+ position           |      |----------------|  +-----------+  +------------+  |- _type           |  |--------------|',
    '   |+ size               |      +----------------+                                 |- _core           |  +--------------+',
    '   |+ type               |           ^                                             |+ position        |',
    '   |+ background         |           |                                             |- _entity         |',
    '   |---------------------|           +------------------------+                    |------------------|',
    '   |+ init               |           |                        |                    |+ position_degree |',
    '   |+ template           |      +-------------------+    +--------------------+    +------------------+',
    '   |- entityTypeContents |      | AttributeInstance |    | IdentifierInstance |',
    '   |- entityBackground   |      |===================|    |====================|',
    '   |- buildIdentifiers   |      |+ name             |    |+ name              |',
    '   |- buildAttributes    |      |+ position         |    |+ position          |',
    '   |- build              |      |+ size             |    |+ size              |',
    '   +---------------------+      |-------------------|    |- _ports            |',
    '          ^                     |+ template         |    |--------------------|',
    '          |                     +-------------------+    +--------------------+',
    '   +-------------------------+',
    '   | EntityTailor            |',
    '   |=========================|',
    '   |<Size>                   |',
    '   |- sizingType             |',
    '   |  sizingName             |           +------------------------+     +-----------------------------+',
    '   |  sizingIdentifiers      |           | Painter                |     | Rectum (Colon)              |',
    '   |  sizingAttributes       |           |========================|     |=============================|',
    '   |  sizingContentsArea     |           |+ foreground            |     |+ callbacks                  |',
    '   |+ sizing                 |           |+ background            |     |- _entities                  |',
    '   |+ reSizing               |           |+ callbacks             |     |- _relationships             |',
    '   |                         |           |- _default              |     |- _default                   |',
    '   |<Position>               |           |------------------------|     |-----------------------------|',
    '   |- positioningName        |           |<Move>                  |     |  ensureCallbacks            |',
    '   |  positioningType        |           |- dragStart             |     |  entities                   |',
    '   |  positioningColumnItems |           |  dragged               |     |  bounds                     |',
    '   |  positioningIdentifiers |           |  dragEnd               |     |  getIdentifier              |',
    '   |  positioningAttributes  |           |  addMoveEvents         |     |  buildRelationshipsWithPort |',
    '   |  deg2rad                |           |  moveEntity            |     |+ data                       |',
    '   |  getPortLineLength      |           |  moveEdges             |     |  draw                       |',
    '   |  getPortLineFrom        |           |                        |     +-----------------------------+',
    '   |  makePortLine           |           |<Draw this.entity>      |',
    '   |  isCorss                |           |  drawGroup             |',
    '   |  getCrossPointCore      |           |                        |',
    '   |  getCrossPoint          |           |<Body>                  |',
    '   |  getEntityLines         |           |  drawBodyCore          |',
    '   |  positioningPort        |           |  drawBody              |',
    '   |  positioningPorts       |           |                        |',
    '   |  positioningEntity      |           |<Name>                  |',
    '   |+ positioning            |           |  drawNameRect          |',
    '   +-------------------------+           |  drawNameText          |',
    '          ^                              |  drawName              |',
    '          |                              |                        |',
    '   +-----------+                         |<Type>                  |',
    '   | Entity    |                         |  drawTypeRect          |',
    '   |===========|                         |  drawTypeText          |',
    '   |- _default |                         |  drawType              |',
    '   |-----------|                         |                        |',
    '   +-----------+                         |<Identifiers>           |',
    '                                         |  drawIdentifiersRect   |',
    '                                         |  drawIdentifiersText   |',
    '                                         |  drawIdentifiers       |',
    '                                         |                        |',
    '                                         |<Attributes>            |',
    '                                         |  drawAttributesRect    |',
    '                                         |  drawAttributesText    |',
    '                                         |  drawAttributes        |',
    '                                         |                        |',
    '                                         |<Port>                  |',
    '                                         |  drawPortsCore         |',
    '                                         |  drawPorts             |',
    '                                         |                        |',
    '                                         |<relationships>         |',
    '                                         |  drawRelationshipsCore |',
    '                                         |  drawRelationships     |',
    '                                         |                        |',
    '                                         |<Draw Main>             |',
    '                                         |+ redraw                |',
    '                                         |+ draw                  |',
    '                                         +------------------------+',
];
